;sets of words tied up to info categories
(def alt_food #{"eat","dinner","lunch","breakfast","food","dine","hungry","hunger","snack","meal","drink","restaraunt","cafe","bar","coffee","beer","wine","svarak","svařák"})
(def alt_toilet #{"wc","restroom","bathroom","toilet","outhouse","lavatory","latrine","water closet"})
(def alt_POI #{"sight", "attraction", "activity", "activities", "tourist","landmark","fun to do","interesting to do","interesting to see","exciting to do","exciting to see","monument"})
(def alt_bike #{"bike","biking","cycle","cycling"})
(def alt_skating #{"skate","skating","rollerblade","rollerblading"})
(def alt_sports #{"sport","exercise","work out","workout","working out","gym","athletic","soccer","tennis","ball","physical"})
(def alt_playground #{"playground","playpen","sandbox","child","kid"})
(def alt_public_transport #{"bus","metro","subway","tube","underground","tram","mhd","public transport","rapid transit","mass transit","get there","get here","travel"})
(def alt_coords #{"coordinates","co-ordinates","coords","co-ords","gps"})
(def alt_parking #{"car","automobile","parking","to park"})
(def alt_dogs #{"dog","pet","pup"})
(def alt_path #{"path","walkway","surface","pavement","trail"})
(def alt_administration #{"responsible","admin","manage","managing","authority","contact"})
(def alt_hours #{"time","hour","open","close","when","how long"})
(def alt_map #{"map","overview","where"})
